[GLOBAL]
pants_version = "2.21.0"
backend_packages = ["pants.backend.python"]

[source]
root_patterns = ["src/python/**/", "scripts/"]

[python]
interpreter_constraints = [">=3.8"]
enable_resolves = true
default_resolve = "global"

[python.resolves]
global = "3rdparty/python/lockfiles/global.lock"
